# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).
  external_labels:
    replica: {{ inventory_hostname }}

# Alertmanager configuration
alerting:
  alert_relabel_configs: 
  - regex: replica 
    action: labeldrop 
  alertmanagers:
    - static_configs:
        - targets: {{ groups['servers'] | product([':9093']) | map('join') | list }}

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "alert_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself. 
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"
    static_configs:
      - targets: {{ groups['servers'] | product([':9090']) | map('join') | list }}

  - job_name: "node-exporter"
    static_configs:
      - targets: {{ groups['servers'] | product([':9100']) | map('join') | list + groups['exporters'] | product([':9100']) | map('join') | list }}

  - job_name: "cadvisor"
    static_configs:
      - targets: {{ groups['servers'] | product([':8080']) | map('join') | list + groups['exporters'] | product([':8080']) | map('join') | list }}